[package]
name = "asynk"
version = "0.1.0"
authors = ["kahgeh.tan <kahgeh.tan@xero.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3", features = ["full"] }
mini-redis = "0.3"