[package]
name = "my-redis"
version = "0.1.0"
authors = ["kahgeh.tan <kahgeh.tan@xero.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.7", features = [ "full"] }
mini-redis = "0.4.0"
